"""add strategy_id to trades table

Revision ID: 3d43b1b27967
Revises: 68c4ae649f1b
Create Date: 2026-02-20 14:05:31.039060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d43b1b27967'
down_revision: Union[str, None] = '68c4ae649f1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
