"""empty message

Revision ID: 68c4ae649f1b
Revises: 8f422dbf621f
Create Date: 2026-02-20 12:19:12.976959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68c4ae649f1b'
down_revision: Union[str, None] = '8f422dbf621f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('strategy_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_trades_strategy_id'), 'trades', ['strategy_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trades_strategy_id'), table_name='trades')
    op.drop_column('trades', 'strategy_id')
    # ### end Alembic commands ###
